### ISSUE TITLE
on debian sid (miss stdint.h)

### ISSUE THREAD

**Issue by Zbsiz** [GNS3/ubridge#23]
⋊> ~/D/ubridge on master ◦ make                                                                                                                                                         14:13:27
gcc -O3 -Wall -DLINUX_RAW   -c -o ubridge.o ubridge.c                                                                                                                                           
gcc -O3 -Wall -DLINUX_RAW   -c -o nio.o nio.c                                                                                                                                                   
gcc -O3 -Wall -DLINUX_RAW   -c -o nio_udp.o nio_udp.c                                                                                                                                           
gcc -O3 -Wall -DLINUX_RAW   -c -o nio_unix.o nio_unix.c                                                                                                                                         
gcc -O3 -Wall -DLINUX_RAW   -c -o nio_ethernet.o nio_ethernet.c                                                                                                                                 
gcc -O3 -Wall -DLINUX_RAW   -c -o nio_tap.o nio_tap.c                                                                                                                                           
gcc -O3 -Wall -DLINUX_RAW   -c -o iniparser/iniparser.o iniparser/iniparser.c                                                                                                                   
gcc -O3 -Wall -DLINUX_RAW   -c -o iniparser/dictionary.o iniparser/dictionary.c                                                                                                                 
gcc -O3 -Wall -DLINUX_RAW   -c -o parse.o parse.c                                                                                                                                               
In file included from parse.c:33:0:                                                                                                                                                             
nio_linux_raw.h:29:5: error: unknown type name ‘uint16_t’                                                                                                                                       
     uint16_t vlan_tp_id;                                                                                                                                                                       
     ^~~~~~~~                                                                                                                                                                                   
nio_linux_raw.h:30:5: error: unknown type name ‘uint16_t’                                                                                                                                       
     uint16_t vlan_tci;                                                                                                                                                                         
     ^~~~~~~~                                                                                                                                                                                   
<builtin>: recipe for target 'parse.o' failed                                                                                                                                                   
make: *** [parse.o] Error 1

------------------------------------------------------------------------------------------
add "#include <stdint.h>"   to the  nio_linux_raw.h
make success

**Comment by ehlers** [comment]
Or add my pull request, that fixes (most) errors introduced by the commit https://github.com/GNS3/ubridge/commit/271ce1a01b7c714b4794dff9eeeea1d59038a74e . Then VLANs tag should be no longer dropped on linux, see https://github.com/GNS3/gns3-server/issues/849

**Comment by grossmj** [comment]
The PR has been merged now.
